web/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('',include('webapp.urls')),
    path('admin/', admin.site.urls),
]

webapp/urls.py
from django.urls import path
from . import views

app_name = 'webapp'
urlpatterns = [
    path("",views.index, name='index'),
    path("index/",views.index, name='index'),
    path("signup/registration",views.registration, name='registration'),
    path("registration",views.registration, name='registration'),
    path("signup/",views.signup, name='signup'),
    path("index/login",views.login, name='login'),
    path("login",views.login, name='login'),
    path("home/",views.home, name='home'),
    path("home/logout",views.logout, name='logout'),
    path("home/view",views.details, name='logout'),
   
    ]

webapp/models.py
from django.db import models

# Create your models here.

class users(models.Model):
    name = models.CharField(max_length=100)
    phone = models.IntegerField(max_length=20)
    

webapp/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.models import User, auth
from django.contrib import messages
from webapp.models import users

# Create your views here.
def index(request):
    return render(request, "index.html")
def signup(request):
    return render(request, "signup.html")
def registration(request):
    print('starting')

    if request.method == "POST":
        uname = request.POST['uname']
        email = request.POST['email']
        pswd = request.POST['pass']
        name = request.POST['name']
        if User.objects.filter(email=email).exists():
            messages.info(request,'email exist please log in')
            return redirect('/signup')
        if User.objects.filter(username=uname).exists():
            messages.info(request,'User name exist')
            return redirect('/signup')
        member = User.objects.create_user(username=uname,email=email,password=pswd,first_name=name)
        member.save()
        print('successful')
        return redirect('/')

    return render(request, "index.html")

def login(request):
    email = request.POST['email']
    pswd = request.POST['pass']
    user = auth.authenticate(username=email, password=pswd)
    if user is not None:
        auth.login(request,user)
        return redirect('/home')
    else:
        messages.info(request,'user not exist')
        return redirect('/')

def home(request):
    return render(request,'home.html')

def logout(request):
    auth.logout(request)
    return redirect('/')

def details(request):
    name = users.name
    phone = users.phone
    redirect('/home')

templates/home.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
	<title>Welcome</title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
<!--===============================================================================================-->	
	<link rel="icon" type="image/png" href="{% static 'images/icons/favicon.ico' %}"/>
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'fonts/font-awesome-4.7.0/css/font-awesome.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'vendor/animate/animate.css' %}">
<!--===============================================================================================-->	
	<link rel="stylesheet" type="text/css" href="{% static 'vendor/css-hamburgers/hamburgers.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'vendor/select2/select2.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'css/util.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
<!--===============================================================================================-->
</head>
<body>
    <div class="limiter">
		<div class="container-login100">
			<div class="wrap-login100">
				<div class="login100-pic js-tilt" data-tilt>
					<img src="{% static 'images/img-01.png' %}" alt="IMG">
                </div>
                <form method="POST" action="logout">
                {% csrf_token %}
                <br> Last Login {{user.last_login}}<br>
                hi {{user.first_name}}<br>
                
               
                <div class="container-login100-form-btn">
                    <button class="login100-form-btn">
                        Logout
                    </button>

                </div>
                </form>
                </div>
                </div>
                </div>
                
<script src="{% static 'vendor/jquery/jquery-3.2.1.min.js' %}"></script>
                <!--===============================================================================================-->
<script src="{% static 'vendor/bootstrap/js/popper.js' %}"></script>
<script src="{% static 'vendor/bootstrap/js/bootstrap.min.js' %}"></script>
                <!--===============================================================================================-->
<script src="{% static 'vendor/select2/select2.min.js' %}"></script>
                <!--===============================================================================================-->
<script src="{% static 'vendor/tilt/tilt.jquery.min.js' %}"></script>
                    
<script >
    $('.js-tilt').tilt({
        scale: 1.1
    })
</script>
<!--===============================================================================================-->
<script src="{% static 'js/main.js' %}"></script>
                
</body>
</html>

templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
	<title>Welcome</title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
<!--===============================================================================================-->	
	<link rel="icon" type="image/png" href="{% static 'images/icons/favicon.ico' %}"/>
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'fonts/font-awesome-4.7.0/css/font-awesome.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'vendor/animate/animate.css' %}">
<!--===============================================================================================-->	
	<link rel="stylesheet" type="text/css" href="{% static 'vendor/css-hamburgers/hamburgers.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'vendor/select2/select2.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'css/util.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
<!--===============================================================================================-->
</head>
<body>
	
	<div class="limiter">
		<div class="container-login100">
			<div class="wrap-login100">
				<div class="login100-pic js-tilt" data-tilt>
					<img src="{% static 'images/img-01.png' %}" alt="IMG">
				</div>

				<form class="login100-form validate-form" method="POST" action="login">
					{% csrf_token %}
					<span class="login100-form-title">
						Member Login
					</span>
					<div style="color: red;">
					{% for message in messages %}
					{{message}}
					{% endfor %}
					</div>

					<div class="wrap-input100" >
					<!--data-validate = "Valid email is required: ex@abc.xyz">-->
						<input class="input100" type="text" name="email" placeholder="User name">
						<span class="focus-input100"></span>
						<span class="symbol-input100">
							<i class="fa fa-envelope" aria-hidden="true"></i>
						</span>
					</div>

					<div class="wrap-input100 validate-input" data-validate = "Password is required">
						<input class="input100" type="password" name="pass" placeholder="Password">
						<span class="focus-input100"></span>
						<span class="symbol-input100">
							<i class="fa fa-lock" aria-hidden="true"></i>
						</span>
					</div>
					
					<div class="container-login100-form-btn">
						<button class="login100-form-btn">
							Login
						</button>
					</div>

					<div class="text-center p-t-12">
						<span class="txt1">
							Forgot
						</span>
						<a class="txt2" href="#">
							Username / Password?
						</a>
					</div>

					<div class="text-center p-t-136">
						<a class="txt2" href="{% url 'webapp:signup' %}">
							Create your Account
							<i class="fa fa-long-arrow-right m-l-5" aria-hidden="true"></i>
						</a>
					</div>
				</form>
			</div>
		</div>
	</div>
	
	

	
<!--===============================================================================================-->	
	<script src="{% static 'vendor/jquery/jquery-3.2.1.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'vendor/bootstrap/js/popper.js' %}"></script>
	<script src="{% static 'vendor/bootstrap/js/bootstrap.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'vendor/select2/select2.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'vendor/tilt/tilt.jquery.min.js' %}"></script>
	<script >
		$('.js-tilt').tilt({
			scale: 1.1
		})
	</script>
<!--===============================================================================================-->
	<script src="{% static 'js/main.js' %}"></script>

</body>
</html>

templates/signup.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Sign Up</title>

    <!-- Font Icon -->
    <link rel="stylesheet" href="{% static 'fonts/material-icon/css/material-design-iconic-font.min.css' %}">

    <!-- Main css -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>

    <div class="main">

        <h1>Sign up</h1>
        <div class="container">
            <div class="sign-up-content">
                <form method="POST" class="signup-form" action="registration">
                    {% csrf_token %}
                    <h2 class="form-title">Sign Up</h2>
                    <div style="align-content: center; color: red;">
                    {% for message in messages %}
                    {{message}}
                    {% endfor %}
                    </div>

                    <div class="form-textbox">
                        <label for="name">Name</label>
                        <input type="text" name="name" id="name" />
                    </div>



                    <div class="form-textbox">
                        <label for="name">User name</label>
                        <input type="text" name="uname" id="uname" />
                    </div>

                    <div class="form-textbox">
                        <label for="email">Email</label>
                        <input type="email" name="email" id="email" />
                    </div>

                    <div class="form-textbox">
                        <label for="pass">Password</label>
                        <input type="password" name="pass" id="pass" />
                    </div>

                    <div class="form-textbox">
                        <input type="submit" name="submit" id="submit" class="submit" value="Create account" />
                    </div>
                </form>

                <p class="loginhere">
                    Already have an account ?<a href="{% url 'webapp:index' %}" class="loginhere-link"> Log in</a>
                </p>
            </div>
        </div>

    </div>

    <!-- JS -->
    <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>
</body><!-- This templates was made by Colorlib (https://colorlib.com) -->
</html>